// <auto-generated />
namespace FileUpload.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddUploadedFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUploadedFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202410251917109_AddUploadedFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
